[package]
name = "rcluster"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]

[dependencies]
bincode = "0.7"
lazy_static = "0.2"
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[dev-dependencies]
rand = "0.3"
