[package]
name = "rcluster-master"
version = "0.1.0"
authors = ["Ravi Shankar <wafflespeanut@gmail.com>"]

[dependencies]
rcluster = { path = "../rcluster" }
structopt = "0.1"
structopt-derive = "0.1"
